{{- range $key, $lelasticDeployment := .Values.lelasticDeployments }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: {{ $lelasticDeployment.name }}
  name: {{ $lelasticDeployment.name }}
  namespace: {{ $.Values.namespace }}
spec:
  strategy: 
    type: Recreate
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $lelasticDeployment.name }}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: {{ $lelasticDeployment.name }}
    spec:
      {{- toYaml $lelasticDeployment.affinityConfig | nindent 6 }}
      containers:
      - name: {{ $lelasticDeployment.name }}
        args:
          - -dcid
          - {{ $.Values.regionId | quote }}
          - -{{ $lelasticDeployment.primaryOrSecondaryArg }}
        image: {{ $.Values.image.registry }}/{{ $.Values.image.repository }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}
        imagePullPolicy: Always
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      hostNetwork: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
      {{- toYaml $lelasticDeployment.tolerations | nindent 8 }}
{{- end }}